### PR TITLE
Include cpanfile, .cgi and .psgi files to test

### PR DESCRIPTION
**Pull request by dboehmer**
I found no way of adding individual files but instead of proposing an `include` option, I suggest adding these file types which would solve my local problem and matches typical Perl files:

- [cpanfile](https://metacpan.org/dist/Module-CPANfile/view/lib/cpanfile.pod)
- [PSGI](https://metacpan.org/pod/PSGI) files
- [CGI](https://metacpan.org/pod/CGI) files

### CODE REVIEW

**Comment by shlomif** [comment]
hi. @dboehmer : did you try using https://metacpan.org/dist/Code-TidyAll instead?

**Comment by dboehmer** [comment]
Never used that before. Do you recommend it over Test-PerlTidy?

I still think my change might be relevant to other Perl devs, too.

**Comment by shlomif** [comment]
> Never used that before. Do you recommend it over Test-PerlTidy?
> 

yes, I do.

> I still think my change might be relevant to other Perl devs, too.

can you add automated tests?

**Comment by shlomif** [comment]
@dboehmer : hi . ping

**Comment by shlomif** [comment]
@dboehmer : hi. I'm going to close this pull-req for now in order to avoid clutter. I can review/accept a new one later. Thanks!

**Comment by dboehmer** [comment]
Thanks for reminding me on this issue :sweat_smile: I’ve just force-pushed two commits to the branch. Do I need to create a new PR or can you reopen this PR? I cannot reopen the PR myself.

**Comment by shlomif** [comment]
> Thanks for reminding me on this issue 😅 I’ve just force-pushed two commits to the branch. Do I need to create a new PR or can you reopen this PR? I cannot reopen the PR myself.

Hi @dboehmer ! The two commits need to be squashed into a single commit first. Afterwards, I suspect we should exclude `.cgi` by default because AFAIK, there can be non-perl5 CGI scripts. Finally, I suggest opening a new pull-request.


Thanks!

**Comment by dboehmer** [comment]
I need to understand why you insist on squashing both together. c0a004d0edea138c8b02afcf3179433ec2aa2de4 fixes issues in the current code and would be relevant even if rejecting the whole idea of this PR while 8f0fc45b5b9a8008b5a229efd44be209d61ef935 is the actual intended change. Why would you reject two commits separating concerns cleanly?

I see the point with .cgi files.

**Comment by shlomif** [comment]
@dboehmer : ah, I misread. My bad! No need for squashing, but note that I had been worried about sort being subject to `locale`/etc. variations

**Comment by dboehmer** [comment]
According to [`perllocale`](https://perldoc.perl.org/perllocale#The-%22use-locale%22-pragma) Perl will never alter the behavior of `sort` unless you `use locale;`. I think you don’t have to worry about sort order. Also the list contains no special characters that are prone to sort order issues like my surname :see_no_evil:

**Pull request closed without merging**
